#!/usr/bin/env ruby
require 'csv'

begin
  require 'awesome_print'
  print_func = :ap
rescue LoadError
  require 'pp'
  print_func = :pp
end

summary = CSV(ARGF, headers: :first_row).each_with_object(Hash.new(0)) do |row, s|
  product_name = row["ProductName"]

  if product_name.empty?
    product_name = row["ItemDescription"] # Tax
  end

  s[product_name] ||= 0
  s[product_name] += row["UnBlendedCost"].to_f
end

summary["Total Include Tax"] = summary.values.sum
summary["Total"] = summary["Total Include Tax"] - summary["Tax of type CT"]

method(print_func).call(summary)
