#!/usr/bin/env ruby
# coding: utf-8

delimiter = "\t"

max_length = []
rows = ARGF.readlines.map do |line|
  line.strip.split(delimiter).tap do |r|
    max_length << r.map(&:length).max
  end
end

(0..rows[0].size).each do |i|
  rows.each_with_index do |r, j|
    printf("%-#{max_length[j]+1}s", r[i])
  end
  puts
end
