#!/bin/sh
# http://hints.macworld.com/article.php?story=20060209130749352

ROOT=${1:-$PWD}
echo `basename $ROOT`
cd `dirname $ROOT` && ls -R `basename $ROOT` | grep ":" | sed -e 's/://' -e 's/[^-][^\/]*\//--/g' -e 's/^//' -e 's/-/|/'
