#!/usr/bin/env ruby
require 'uri'

case $0
when /encode/
  method = URI.method(:encode_www_form_component)
when /decode/
  method = URI.method(:decode_www_form_component)
else
  puts "Can't find method for $0"
  exit 1
end

str = ARGV.any? ? ARGV : STDIN
str.each do |a|
  puts method.call(a)
end
